### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by syedsimanta03** [one-dark/vscode-one-dark-theme#28]
1. Normal text should be white color
2. Comment isn't readable when italic - should be normal text or bold or user option to select
3.  Also can make the HTML look better making class id tag colorful

[Image](https://imgur.com/a/oYchfDF)
[Image](https://imgur.com/a/2bOUTx9)

<blockquote class="imgur-embed-pub" lang="en" data-id="a/oYchfDF" data-context="false" ><a href="//imgur.com/a/oYchfDF"></a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

<blockquote class="imgur-embed-pub" lang="en" data-id="a/2bOUTx9" data-context="false" ><a href="//imgur.com/a/2bOUTx9"></a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

**Comment by mskelton** [comment]
> Normal text should be white color

I assume by white you mean `#fff` rather than the current color which is white with a touch of gray.  This is intentional so it isn't overpoweringly white thus making it a bit nicer on the eyes.

> Comment isn't readable when italic - should be normal text or bold or user option to select

This is kind of the whole point, making comments less prominent so the actual code stands out.  The font you are using happens to have really obnoxious italics, but fonts like Operator Mono, Fira Code, Dank Mono, etc. look just fine with the italics.  The screenshot in the readme uses Operator Mono which shows very readable italics.

> Also can make the HTML look better making class id tag colorful

Not sure what you mean here, but differentiating colors based on the type of attribute isn't something that I believe is even possible nor would it be a good idea in my opinion.

> `updatedOrder` can be the _same color_ as 1st one when `const updatedOrder` has the main color I want when reuse this var

You might have `editor.semanticHighlighting.enabled` set to false.  When it is set to `true` or `configuredByTheme` the editor will determine that the `updatedOrder` variable is a const and color it properly.

**Comment by syedsimanta03** [comment]
Man, I can't easily believe this theme exists @mskelton  !!! You fixed all problem. Operator Mono looks super cool here. This theme just changed my mind and uninstalled material theme.  Code is more readable and easy to fix and check things.

I am a UI, graphics  designer and coder. if you have any side project or want to develop more apps like this I will join & love to help you. Thanks for your hard work. You are awesome.

**Comment by mskelton** [comment]
Thanks @syedsimanta03!  I don't have any other UI heavy things planned at the moment, but I'll keep you in mind if I do.
