### ISSUE TITLE
Update logo to distinguish from other themes

### ISSUE THREAD

**Issue by will-stone** [one-dark/vscode-one-dark-theme#33]
Hi @mskelton 👋 

I'll just leave this here as a placeholder; I'll see what I can come up with. One of the ideas that I proposed on the _other issue_ was to change the atom for a "1", but I'll see what else I can come up with.

Thanks,

Will.

> See https://github.com/Binaryify/OneDark-Pro/issues/550 for detailed discussion.

**Comment by mskelton** [comment]
Thanks a ton @will-stone!  You rock!

**Comment by will-stone** [comment]
This is the sort of thing I was thinking about:
<img src="https://user-images.githubusercontent.com/654103/118644028-3597f400-b7d5-11eb-9351-9fcc201cede7.png" alt="" width="150" height="150" />

But let me know the direction you're thinking 🙂

**Comment by mskelton** [comment]
@will-stone I'm not sure I really want to depart that much from the logo that is currently in use as I don't want to sacrifice recognizability.  A couple random ideas that come to mind:

1. The atom shape with the "1" in the middle instead of the dot
2. The atom shape with a set of curly brackets in the middle
3. A modified atom shape.  Perhaps something [like this](https://images.theconversation.com/files/247813/original/file-20181128-32221-536vvw.jpg?ixlib=rb-1.1.0&q=45&auto=format&w=320&h=267&fit=crop) but using the same gray and purple scheme.

Thoughts?

**Comment by will-stone** [comment]
I don't think I'm currently going to be able to help with this. Thank you.
