### ISSUE TITLE
Highlight around textboxes

### ISSUE THREAD

**Issue by dorudumitru-hh** [one-dark/vscode-one-dark-theme#4]
Can you please add highlight around textboxes and underline selected tabs as in your intellij version of the theme?

**Comment by mskelton** [comment]
I'm planning to do a complete revamp of this theme to improve the consistency between this and my JetBrains theme.  One of the first things will be to improve the editor styles including what you have mentioned.  Please be patient as I will get to this, but it will be a little bit due to my busy schedule right now.

Thanks for opening this issue!

**Comment by mskelton** [comment]
@hhquerybuilder Just to give an update on this issue.  As I mentioned I am still thinking about this and working towards getting this fixed in the new theme version.  I released the new theme today which does require you to uninstall the old theme and install the new theme.  When you update to the latest version of the old theme it will prompt you to update to the new theme.

I haven't actually got to fixing this specific issue, but now that I have the new theme setup, I'll try to get to this next.

Thanks for your patience!

**Comment by mskelton** [comment]
I just pushed some commits to add the border colors you suggested.  Thanks for the suggestion and for the patience waiting for this to get finished.  The changes will go out in the next release (probably a couple days from now).

**Comment by mskelton** [comment]
@all-contributors please add @hhquerybuilder to design

**Comment by mskelton** [comment]
@all-contributors please add @hhquerybuilder to design

**Comment by mskelton** [comment]
Version 1.2.0 released with these changes.  Once again, thanks for your patience!
